"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var book_controller_1 = require("../controllers/book.controller");
var router = (0, express_1.Router)();
var bookController = new book_controller_1.BookController();
router.get('/', bookController.getBooks);
router.get('/:bookid', bookController.getBookById);
router.post('/create', bookController.createBook);
exports.default = router;
